/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RageQuitCounterInterface extends Interface {
    getFunction(nameOrSignature: "getMyRageQuitCount" | "getRageQuitCount" | "getTotalRageQuits" | "rageQuitCount" | "recordBatchRageQuit" | "recordRageQuit" | "totalRageQuits"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchRageQuitRecorded" | "RageQuitRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'getMyRageQuitCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRageQuitCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalRageQuits', values?: undefined): string;
encodeFunctionData(functionFragment: 'rageQuitCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'recordBatchRageQuit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordRageQuit', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRageQuits', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getMyRageQuitCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRageQuitCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalRageQuits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rageQuitCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordBatchRageQuit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordRageQuit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRageQuits', data: BytesLike): Result;
  }

  
    export namespace BatchRageQuitRecordedEvent {
      export type InputTuple = [user: AddressLike, count: BigNumberish, newTotal: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, count: bigint, newTotal: bigint, timestamp: bigint];
      export interface OutputObject {user: string, count: bigint, newTotal: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RageQuitRecordedEvent {
      export type InputTuple = [user: AddressLike, newCount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [user: string, newCount: bigint, timestamp: bigint];
      export interface OutputObject {user: string, newCount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RageQuitCounter extends BaseContract {
    
    connect(runner?: ContractRunner | null): RageQuitCounter;
    waitForDeployment(): Promise<this>;

    interface: RageQuitCounterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getMyRageQuitCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRageQuitCount: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getTotalRageQuits: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rageQuitCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    recordBatchRageQuit: TypedContractMethod<
      [count: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordRageQuit: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalRageQuits: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getMyRageQuitCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRageQuitCount'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalRageQuits'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rageQuitCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'recordBatchRageQuit'): TypedContractMethod<
      [count: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordRageQuit'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalRageQuits'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'BatchRageQuitRecorded'): TypedContractEvent<BatchRageQuitRecordedEvent.InputTuple, BatchRageQuitRecordedEvent.OutputTuple, BatchRageQuitRecordedEvent.OutputObject>;
getEvent(key: 'RageQuitRecorded'): TypedContractEvent<RageQuitRecordedEvent.InputTuple, RageQuitRecordedEvent.OutputTuple, RageQuitRecordedEvent.OutputObject>;

    filters: {
      
      'BatchRageQuitRecorded(address,uint256,uint256,uint256)': TypedContractEvent<BatchRageQuitRecordedEvent.InputTuple, BatchRageQuitRecordedEvent.OutputTuple, BatchRageQuitRecordedEvent.OutputObject>;
      BatchRageQuitRecorded: TypedContractEvent<BatchRageQuitRecordedEvent.InputTuple, BatchRageQuitRecordedEvent.OutputTuple, BatchRageQuitRecordedEvent.OutputObject>;
    

      'RageQuitRecorded(address,uint256,uint256)': TypedContractEvent<RageQuitRecordedEvent.InputTuple, RageQuitRecordedEvent.OutputTuple, RageQuitRecordedEvent.OutputObject>;
      RageQuitRecorded: TypedContractEvent<RageQuitRecordedEvent.InputTuple, RageQuitRecordedEvent.OutputTuple, RageQuitRecordedEvent.OutputObject>;
    
    };
  }